// <auto-generated />
namespace PIZZERIA_DA_GIGI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AggiornamentoModello : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiornamentoModello));
        
        string IMigrationMetadata.Id
        {
            get { return "202403121344108_AggiornamentoModello"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
