// <auto-generated />
namespace PIZZERIA_DA_GIGI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agg));
        
        string IMigrationMetadata.Id
        {
            get { return "202403141342525_agg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
